/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as DamageCalculatorImport } from './routes/damage-calculator'
import { Route as AugmentsImport } from './routes/augments'
import { Route as ActionsImport } from './routes/actions'
import { Route as IndexImport } from './routes/index'
import { Route as UnitsIndexImport } from './routes/units.index'
import { Route as UnitsUnitIdImport } from './routes/units.$unitId'

// Create/Update Routes

const DamageCalculatorRoute = DamageCalculatorImport.update({
  id: '/damage-calculator',
  path: '/damage-calculator',
  getParentRoute: () => rootRoute,
} as any)

const AugmentsRoute = AugmentsImport.update({
  id: '/augments',
  path: '/augments',
  getParentRoute: () => rootRoute,
} as any)

const ActionsRoute = ActionsImport.update({
  id: '/actions',
  path: '/actions',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const UnitsIndexRoute = UnitsIndexImport.update({
  id: '/units/',
  path: '/units/',
  getParentRoute: () => rootRoute,
} as any)

const UnitsUnitIdRoute = UnitsUnitIdImport.update({
  id: '/units/$unitId',
  path: '/units/$unitId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/actions': {
      id: '/actions'
      path: '/actions'
      fullPath: '/actions'
      preLoaderRoute: typeof ActionsImport
      parentRoute: typeof rootRoute
    }
    '/augments': {
      id: '/augments'
      path: '/augments'
      fullPath: '/augments'
      preLoaderRoute: typeof AugmentsImport
      parentRoute: typeof rootRoute
    }
    '/damage-calculator': {
      id: '/damage-calculator'
      path: '/damage-calculator'
      fullPath: '/damage-calculator'
      preLoaderRoute: typeof DamageCalculatorImport
      parentRoute: typeof rootRoute
    }
    '/units/$unitId': {
      id: '/units/$unitId'
      path: '/units/$unitId'
      fullPath: '/units/$unitId'
      preLoaderRoute: typeof UnitsUnitIdImport
      parentRoute: typeof rootRoute
    }
    '/units/': {
      id: '/units/'
      path: '/units'
      fullPath: '/units'
      preLoaderRoute: typeof UnitsIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/actions': typeof ActionsRoute
  '/augments': typeof AugmentsRoute
  '/damage-calculator': typeof DamageCalculatorRoute
  '/units/$unitId': typeof UnitsUnitIdRoute
  '/units': typeof UnitsIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/actions': typeof ActionsRoute
  '/augments': typeof AugmentsRoute
  '/damage-calculator': typeof DamageCalculatorRoute
  '/units/$unitId': typeof UnitsUnitIdRoute
  '/units': typeof UnitsIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/actions': typeof ActionsRoute
  '/augments': typeof AugmentsRoute
  '/damage-calculator': typeof DamageCalculatorRoute
  '/units/$unitId': typeof UnitsUnitIdRoute
  '/units/': typeof UnitsIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/actions'
    | '/augments'
    | '/damage-calculator'
    | '/units/$unitId'
    | '/units'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/actions'
    | '/augments'
    | '/damage-calculator'
    | '/units/$unitId'
    | '/units'
  id:
    | '__root__'
    | '/'
    | '/actions'
    | '/augments'
    | '/damage-calculator'
    | '/units/$unitId'
    | '/units/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActionsRoute: typeof ActionsRoute
  AugmentsRoute: typeof AugmentsRoute
  DamageCalculatorRoute: typeof DamageCalculatorRoute
  UnitsUnitIdRoute: typeof UnitsUnitIdRoute
  UnitsIndexRoute: typeof UnitsIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActionsRoute: ActionsRoute,
  AugmentsRoute: AugmentsRoute,
  DamageCalculatorRoute: DamageCalculatorRoute,
  UnitsUnitIdRoute: UnitsUnitIdRoute,
  UnitsIndexRoute: UnitsIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/actions",
        "/augments",
        "/damage-calculator",
        "/units/$unitId",
        "/units/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/actions": {
      "filePath": "actions.tsx"
    },
    "/augments": {
      "filePath": "augments.tsx"
    },
    "/damage-calculator": {
      "filePath": "damage-calculator.tsx"
    },
    "/units/$unitId": {
      "filePath": "units.$unitId.tsx"
    },
    "/units/": {
      "filePath": "units.index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
